server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
         - id: ai-summary-service
           uri: lb://ai-summary-service
           predicates:
             - Path=/api/ai/**

         - id: news-service
           uri: lb://news-service
           predicates:
            - Path=/api/news/**
         
         - id: user-auth-service
           uri: lb://user-auth-service
           predicates:
            - Path=/api/auth/**, /api/bookmarks/**, /api/users/**, /api/history/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/