server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # --- ADD THIS ENTIRE SECTION ---
      globalcors:
        cors-configurations:
          '[/**]': # Apply to all paths
            allowed-origins: "http://localhost:5173,https://nexus-news-ten.vercel.app" # The origin of your React app
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
      # --- END OF NEW SECTION ---
      routes:
         - id: ai-summary-service
           uri: lb://ai-summary-service
           predicates:
             - Path=/api/ai/**

         - id: news-service
           uri: lb://news-service
           predicates:
            - Path=/api/news/**
         
         - id: user-auth-service
           uri: lb://user-auth-service
           predicates:
            - Path=/api/auth/**, /api/bookmarks/**, /api/users/**, /api/history/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/